In [1]:
import numpy as np
import pandas as pd

Dataframe: 2-D structure of data consisting rows and columns. In dataframe every single row or column called series

Creating Dataframe:

In [28]:
#using lists
student_data = [[100,80,10],[90,70,7],[120,100,14],[60,50,2]]
student = pd.DataFrame(student_data,columns = ["IQ","Marks","Package"])
student

    IQ  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   60     50        2

In [52]:
#using dict 
student_dict = { "iq": [90,80,70,0,0],
                 "Marks":[88,74,84,0,0],
                  "Package":[76,5,4,0,0]
               
               }
student_info=pd.DataFrame(student_dict)
student_info

   iq  Marks  Package
0  90     88       76
1  80     74        5
2  70     84        4
3   0      0        0
4   0      0        0

In [11]:
#using read_csv
movies = pd.read_csv("movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [13]:
 ipl = pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

Dataframe Attribute and Methods

In [16]:
#shape
movies.shape
ipl.shape  # 950 total match and divided into 20 columns

(950, 20)

In [18]:
#dtypes
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [19]:
ipl.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [26]:
#index
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [22]:
#columns
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [24]:
#values
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In [27]:
student_data

[[100, 80, 10], [90, 70, 7], [120, 100, 14], [60, 50, 2]]

In [29]:
student.values

array([[100,  80,  10],
       [ 90,  70,   7],
       [120, 100,  14],
       [ 60,  50,   2]], dtype=int64)

In [30]:
#head and tail
movies.head

<bound method NDFrame.head of                                    title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224
1                            Battalion 609   tt9472208
2     The Accidental Prime Minister (film)   tt6986710
3                          Why Cheat India   tt8108208
4                          Evening Shadows   tt6028796
...                                    ...         ...
1624                 Tera Mera Saath Rahen   tt0301250
1625                  Yeh Zindagi Ka Safar   tt0298607
1626                       Sabse Bada Sukh   tt0069204
1627                                 Daaka  tt10833860
1628                              Humsafar   tt2403201

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1                                                   NaN
2     https://upload.wikimedia.org/wikipedia/en/thum...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4                                                   NaN
...                                                 ...
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...
1625  https://upload.wikimedia.org/wikipedia/en/thum...
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1           https://en.wikipedia.org/wiki/Battalion_609
2     https://en.wikipedia.org/wiki/The_Accidental_P...
3         https://en.wikipedia.org/wiki/Why_Cheat_India
4         https://en.wikipedia.org/wiki/Evening_Shadows
...                                                 ...
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627                https://en.wikipedia.org/wiki/Daaka
1628             https://en.wikipedia.org/wiki/Humsafar

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                     Battalion 609                  Battalion 609         0
2     The Accidental Prime Minister  The Accidental Prime Minister         0
3                   Why Cheat India                Why Cheat India         0
4                   Evening Shadows                Evening Shadows         0
...                             ...                            ...       ...
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0
1626                Sabse Bada Sukh                Sabse Bada Sukh         0
1627                          Daaka                          Daaka         0
1628                       Humsafar                       Humsafar         0

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112
1                2019     131               War          4.1          73
2                2019     112   Biography|Drama          6.1        5549
3                2019     121       Crime|Drama          6.0        1891
4                2018     102             Drama          7.3         280
...               ...     ...               ...          ...         ...
1624             2001     148             Drama          4.9         278
1625             2001     146             Drama          3.0         133
1626             2018      \N      Comedy|Drama          6.1          13
1627             2019     136            Action          7.4          38
1628             2011      35     Drama|Romance          9.0        2968

                                                  story  \
0     Divided over five chapters  the film chronicle...
1     The story revolves around a cricket match betw...
2     Based on the memoir by Indian policy analyst S...
3     The movie focuses on existing malpractices in ...
4     While gay rights and marriage equality has bee...
...                                                 ...
1624  Raj Dixit lives with his younger brother  Rahu...
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
0     Indian army special forces execute a covert op...     NaN
1     The story of Battalion 609 revolves around a c...     NaN
2     Explores Manmohan Singh's tenure as the Prime ...     NaN
3     The movie focuses on existing malpractices in ...     NaN
4     Under the 'Evening Shadows'  truth often plays...     NaN
...                                                 ...     ...
1624  A man is torn between his handicapped brother ...     NaN
1625  A singer finds out she was adopted when the ed...     NaN
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors  \
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...                                                 ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                          Gippy Grewal|Zareen Khan|
1628                                        Fawad Khan|

            wins_nominations              release_date
0                     4 wins     11 January 2019 (USA)
1                        NaN   11 January 2019 (India)
2                        NaN     11 January 2019 (USA)
3                        NaN     18 January 2019 (USA)
4     17 wins & 1 nomination   11 January 2019 (India)
...                      ...                       ...
1624                     NaN   7 November 2001 (India)
1625                     NaN  16 November 2001 (India)
1626                     NaN                       NaN
1627                     NaN     1 November 2019 (USA)
1628                     NaN     TV Series (2011–2012)

[1629 rows x 18 columns]>

In [31]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [32]:
movies.tail

<bound method NDFrame.tail of                                    title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224
1                            Battalion 609   tt9472208
2     The Accidental Prime Minister (film)   tt6986710
3                          Why Cheat India   tt8108208
4                          Evening Shadows   tt6028796
...                                    ...         ...
1624                 Tera Mera Saath Rahen   tt0301250
1625                  Yeh Zindagi Ka Safar   tt0298607
1626                       Sabse Bada Sukh   tt0069204
1627                                 Daaka  tt10833860
1628                              Humsafar   tt2403201

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...
1                                                   NaN
2     https://upload.wikimedia.org/wikipedia/en/thum...
3     https://upload.wikimedia.org/wikipedia/en/thum...
4                                                   NaN
...                                                 ...
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...
1625  https://upload.wikimedia.org/wikipedia/en/thum...
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1           https://en.wikipedia.org/wiki/Battalion_609
2     https://en.wikipedia.org/wiki/The_Accidental_P...
3         https://en.wikipedia.org/wiki/Why_Cheat_India
4         https://en.wikipedia.org/wiki/Evening_Shadows
...                                                 ...
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh
1627                https://en.wikipedia.org/wiki/Daaka
1628             https://en.wikipedia.org/wiki/Humsafar

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                     Battalion 609                  Battalion 609         0
2     The Accidental Prime Minister  The Accidental Prime Minister         0
3                   Why Cheat India                Why Cheat India         0
4                   Evening Shadows                Evening Shadows         0
...                             ...                            ...       ...
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0
1626                Sabse Bada Sukh                Sabse Bada Sukh         0
1627                          Daaka                          Daaka         0
1628                       Humsafar                       Humsafar         0

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112
1                2019     131               War          4.1          73
2                2019     112   Biography|Drama          6.1        5549
3                2019     121       Crime|Drama          6.0        1891
4                2018     102             Drama          7.3         280
...               ...     ...               ...          ...         ...
1624             2001     148             Drama          4.9         278
1625             2001     146             Drama          3.0         133
1626             2018      \N      Comedy|Drama          6.1          13
1627             2019     136            Action          7.4          38
1628             2011      35     Drama|Romance          9.0        2968

                                                  story  \
0     Divided over five chapters  the film chronicle...
1     The story revolves around a cricket match betw...
2     Based on the memoir by Indian policy analyst S...
3     The movie focuses on existing malpractices in ...
4     While gay rights and marriage equality has bee...
...                                                 ...
1624  Raj Dixit lives with his younger brother  Rahu...
1625  Hindi pop-star  Sarina Devan  lives a wealthy ...
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
0     Indian army special forces execute a covert op...     NaN
1     The story of Battalion 609 revolves around a c...     NaN
2     Explores Manmohan Singh's tenure as the Prime ...     NaN
3     The movie focuses on existing malpractices in ...     NaN
4     Under the 'Evening Shadows'  truth often plays...     NaN
...                                                 ...     ...
1624  A man is torn between his handicapped brother ...     NaN
1625  A singer finds out she was adopted when the ed...     NaN
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors  \
0     Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1     Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2     Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3     Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4     Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...                                                 ...
1624  Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625  Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                          Gippy Grewal|Zareen Khan|
1628                                        Fawad Khan|

            wins_nominations              release_date
0                     4 wins     11 January 2019 (USA)
1                        NaN   11 January 2019 (India)
2                        NaN     11 January 2019 (USA)
3                        NaN     18 January 2019 (USA)
4     17 wins & 1 nomination   11 January 2019 (India)
...                      ...                       ...
1624                     NaN   7 November 2001 (India)
1625                     NaN  16 November 2001 (India)
1626                     NaN                       NaN
1627                     NaN     1 November 2019 (USA)
1628                     NaN     TV Series (2011–2012)

[1629 rows x 18 columns]>

In [33]:
movies.tail(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [35]:
#sample: it is used to randomly select item from given data set
movies.sample(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1318,Khakee,tt0347332,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Khakee,Khakee,Khakee,0,2004,174,Action|Crime|Drama,7.4,14234,DCP Anant Shrivastav (Amitabh Bachchan) has be...,A team of police force escorts an alleged terr...,The Protector...The Lover...The Destroyer,Amitabh Bachchan|Akshay Kumar|Ajay Devgn|Aishw...,21 nominations,23 January 2004 (USA)
316,Rustom (film),tt5165344,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rustom_(film),Rustom,Rustom,0,2016,148,Crime|Drama|Thriller,7.1,20764,Naval officer Rustom Pavri returns from his po...,A naval officer returns home to find out about...,NaN,Ileana D'Cruz|Akshay Kumar|Manoj Bajpayee|Shar...,1 win & 4 nominations,12 August 2016 (India)
1424,Chura Liyaa Hai Tumne,tt0345043,https://upload.wikimedia.org/wikipedia/en/c/c9...,https://en.wikipedia.org/wiki/Chura_Liyaa_Hai_...,Chura Liyaa Hai Tumne,Chura Liyaa Hai Tumne,0,2003,143,Action|Drama|Mystery,3.7,443,A beautiful captive young woman name Tina Kha...,A beautiful captive young woman name Tina Kha...,NaN,Zayed Khan|Esha Deol|Gulshan Grover|Rakhi Sawa...,1 nomination,21 March 2003 (India)
773,Double Dhamaal,tt1728239,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Double_Dhamaal,Double Dhamaal,Double Dhamaal,0,2011,138,Comedy|Crime|Drama,3.8,3105,After losing a huge sum to a police officer K...,Four slackers decide to avenge their humiliati...,NaN,Sanjay Dutt|Riteish Deshmukh|Arshad Warsi|Jave...,1 win & 1 nomination,1 July 2011 (USA)
647,Gori Tere Pyaar Mein,tt2275794,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gori_Tere_Pyaar_...,Gori Tere Pyaar Mein!,Gori Tere Pyaar Mein!,0,2013,150,Comedy|Drama|Romance,5.0,3250,Sriram Venkat is the most shallow guy on earth...,Self-centered Sriram Venkat changes his outloo...,NaN,Imran Khan|Kareena Kapoor|Nizhalgal Ravi|Anupa...,1 nomination,22 November 2013 (USA)
1016,Rock On!!,tt1230165,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rock_On!!_(2008_...,Rock On!!,Rock On!!,0,2008,145,Drama|Music,7.8,19565,Sakshi Shroff the lonely and neglected wife o...,Four friends reunite to relive their moments o...,Live your dream,Arjun Rampal|Farhan Akhtar|Luke Kenny|Purab Ko...,16 wins & 19 nominations,29 August 2008 (USA)
60,Yaaram (2019 film),tt11007050,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yaaram_(2019_film),#Yaaram,#Yaaram,0,2019,\N,Comedy|Romance,5.7,7,All set for an arranged marriage Rohit Bajaj ...,All set for an arranged marriage Rohit Bajaj ...,NaN,Siddhanth Kapoor|Prateik|Anita Raj|Ishita Raj|...,NaN,NaN
1193,Mere Jeevan Saathi (2006 film),tt0418880,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Jeevan_Saat...,Mere Jeevan Saathi,Mere Jeevan Saathi,0,2006,129,Drama|Music|Romance,3.5,824,Back in college Natasha was obsessed with Vic...,Back in college Natasha was obsessed with Vic...,Surrender to love,Akshay Kumar|Karisma Kapoor|Ameesha Patel|Guls...,NaN,3 February 2006 (India)
154,Pihu,tt8458202,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pihu_(film),Pihu,Pihu,0,2018,91,Drama|Thriller,6.7,1582,The social thriller starring the two year baby...,The social thriller starring the two year baby...,NaN,Rahul Bagga|Pihu Myra Vishwakarma|,NaN,16 November 2018 (India)
1212,Yun Hota Toh Kya Hota,tt0470614,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yun_Hota_Toh_Kya...,What If?,Yun Hota Toh Kya Hota,0,2006,115,Drama,6.7,584,The Visa papers have arrived for stock broker ...,The Visa papers have arrived for stock broker ...,NaN,Paresh Rawal|Konkona Sen Sharma|Jimmy Sheirgil...,NaN,21 July 2006 (USA)

In [37]:
#info: it gives information about dataframe
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [38]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [39]:
#describe
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [40]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [44]:
#isnull
movies.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [45]:
movies.isnull().sum()  # it will tell how many missing values in certain columns

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [48]:
#duplicated
movies.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1624    False
1625    False
1626    False
1627    False
1628    False
Length: 1629, dtype: bool

In [50]:
movies.duplicated().sum()  #by applying sum() it will give toatal no of duplicated rows

0

In [54]:
student_info.duplicated().sum()

1

In [55]:
#rename
student_info

   iq  Marks  Package
0  90     88       76
1  80     74        5
2  70     84        4
3   0      0        0
4   0      0        0

In [61]:
student_info.rename(columns = {"Marks":"Percent","Package":"LPA"})  #temporary change

   iq  Percent  LPA
0  90       88   76
1  80       74    5
2  70       84    4
3   0        0    0
4   0        0    0

In [62]:
#to change it permanently
student_info.rename(columns = {"Marks":"Percent","Package":"LPA"},inplace = True)

In [63]:
student_info

   iq  Percent  LPA
0  90       88   76
1  80       74    5
2  70       84    4
3   0        0    0
4   0        0    0

Dta_frame maths method:

In [3]:
import numpy as np
import pandas as pd

In [50]:
#using dict 
student_dict = { 
    "Name": ["Preeti","Kritika","Kusum","Nibha","Sanisha"],
    "iq": [90,80,70,0,0],
    "Marks":[88,74,84,0,0],
    "Package":[76,5,4,0,0]
               
               }
student_info=pd.DataFrame(student_dict)
student_info.set_index("Name",inplace=True)
student_info#set.index helps to set index column and to remove default index

         iq  Marks  Package
Name
Preeti   90     88       76
Kritika  80     74        5
Kusum    70     84        4
Nibha     0      0        0
Sanisha   0      0        0

In [5]:
#sum -> axis argument
movies = pd.read_csv("movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [7]:
student_info.sum()  #it will aplly sum by column wise  by default

iq         240
Marks      246
Package     85
dtype: int64

In [11]:
#to do row wise sum
student_info.sum(axis=1)

0    254
1    159
2    158
3      0
4      0
dtype: int64

In [14]:
student_info.mean(axis = 1)

0    84.666667
1    53.000000
2    52.666667
3     0.000000
4     0.000000
dtype: float64

In [15]:
student_info.median()

iq         70.0
Marks      74.0
Package     4.0
dtype: float64

In [17]:
student_info.mode()

   iq  Marks  Package
0   0      0        0

In [18]:
student_info.min()

iq         0
Marks      0
Package    0
dtype: int64

In [19]:
student_info.max()

iq         90
Marks      88
Package    76
dtype: int64

In [20]:
student_info.std()

iq         44.384682
Marks      45.201770
Package    33.060551
dtype: float64

In [21]:
student_info.var()

iq         1970.0
Marks      2043.2
Package    1093.0
dtype: float64

Selecting a single col from dataframe:

In [22]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [23]:
movies["title_x"]  #fetching single column

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [24]:
type(movies["title_x"])

pandas.core.series.Series

In [27]:
ipl = pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [28]:
ipl["Venue"]  #single column will be Series

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: object

In [29]:
#multiples columns
movies[["title_x","year_of_release","actors"]]  #multiple column will be dataframe

,title_x,year_of_release,actors
0,Uri: The Surgical Strike,2019,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,2019,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),2019,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,2019,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,2018,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,2001,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,2001,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,2018,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,2019,Gippy Grewal|Zareen Khan|
1628,Humsafar,2011,Fawad Khan|

In [30]:
ipl[["Team1","Team2","WinningTeam"]]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

Selecting rows from a Dataframe:
1. iloc:searching using index positions
2. loc : searches using index labels

In [32]:
#single row
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [33]:
#multiple row
movies.iloc[0:6]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [34]:
#fancy indexing
movies.iloc[[7,4,0]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [51]:
#loc:fetching row using index label
student_info

         iq  Marks  Package
Name
Preeti   90     88       76
Kritika  80     74        5
Kusum    70     84        4
Nibha     0      0        0
Sanisha   0      0        0

In [53]:
student_info.loc["Sanisha"]

iq         0
Marks      0
Package    0
Name: Sanisha, dtype: int64

In [55]:
student_info["Preeti":"Nibha"]  #nibha also will be included

        iq  Marks  Package
Name
Preeti  90     88       76
Kusum   70     84        4

In [56]:
student_info["Preeti":"Kusum":2]

        iq  Marks  Package
Name
Preeti  90     88       76
Kusum   70     84        4

In [60]:
student_info.iloc[0]  #0 and Preeti points same row

iq         90
Marks      88
Package    76
Name: Preeti, dtype: int64

Selecting both rows and columns:

In [61]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [62]:
movies.iloc[0:3,0:3]  #[rows,columnc]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [63]:
movies.loc[0:3,"title_x"]

0                Uri: The Surgical Strike
1                           Battalion 609
2    The Accidental Prime Minister (film)
3                         Why Cheat India
Name: title_x, dtype: object

#to use default index given by dataframe we will use iloc
and to use index given by us we will use loc

Filtering a dataframe:

In [65]:
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [69]:
#find all the final winners
mask = ipl["MatchNumber"]=="Final"
new_df = ipl[mask]
new_df[["Season","WinningTeam"]]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [83]:
#whole code can be done in single line
ipl[ipl["MatchNumber"] == "final"][["Season", "WinningTeam"]]

Empty DataFrame
Columns: [Season, WinningTeam]
Index: []

In [82]:
#how manmy super over occured
ipl[ipl["SuperOver"] == "Y"].shape[0]

14

In [91]:
#how many matches has csk won in kolkata
ipl[(ipl["City"] == "Kolkata")&(ipl["WinningTeam"] == "Chennai Super Kings")].shape[0]

5

In [101]:
#toss winner is match winner in percentage
(ipl[ipl["TossWinner"]== ipl["WinningTeam"]].shape[0] / ipl.shape[0])*100
#(ipl[ipl["TossWinner"] == ipl["WinningTeam"]].shape[0] / ipl.shape[0]) * 100

51.473684210526315

In [103]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [108]:
#movies with rating higher than 8 and votes>10000
movies[(movies["imdb_rating"]> 8) & (movies["imdb_votes"]>10000)].shape[0]

43

In [110]:
#action movies with ratings
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [125]:
mask1=movies["genres"].str.split("|").apply(lambda x: "Action" in x)
mask2 = movies["imdb_rating"]>7.5
movies[mask1 & mask2].shape[0]

33

In [126]:
#another method
mask1=movies["genres"].str.contains("Action")
mask2 = movies["imdb_rating"]>7.5
movies[mask1 & mask2].shape[0]

33

Adding new columns:

In [128]:
movies["Country"] = "India"
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

In [137]:
#new columns from existing one
#movies["actors"].str.split().apply(lambda x:x[0])
movies.dropna(inplace=True)
movies["lead_actor"]= movies["actors"].str.split().apply(lambda x:x[0])
movies.head

<bound method NDFrame.head of                       title_x     imdb_id  \
11                  Gully Boy   tt2395469
34              Yeh Hai India   tt5525846
37          Article 15 (film)  tt10324144
87                    Aiyaary   tt6774212
96           Raid (2018 film)   tt7363076
...                       ...         ...
1600                   Kasoor   tt0272688
1601         Maya (2001 film)   tt0299027
1607  Nayak (2001 Hindi film)   tt0291376
1621                  Tum Bin   tt0290326
1623                 Zubeidaa   tt0255713

                                            poster_path  \
11    https://upload.wikimedia.org/wikipedia/en/thum...
34    https://upload.wikimedia.org/wikipedia/en/thum...
37    https://upload.wikimedia.org/wikipedia/en/thum...
87    https://upload.wikimedia.org/wikipedia/en/thum...
96    https://upload.wikimedia.org/wikipedia/en/thum...
...                                                 ...
1600  https://upload.wikimedia.org/wikipedia/en/thum...
1601  https://upload.wikimedia.org/wikipedia/en/thum...
1607  https://upload.wikimedia.org/wikipedia/en/thum...
1621  https://upload.wikimedia.org/wikipedia/en/thum...
1623  https://upload.wikimedia.org/wikipedia/en/thum...

                                              wiki_link  \
11              https://en.wikipedia.org/wiki/Gully_Boy
34          https://en.wikipedia.org/wiki/Yeh_Hai_India
37      https://en.wikipedia.org/wiki/Article_15_(film)
87                https://en.wikipedia.org/wiki/Aiyaary
96       https://en.wikipedia.org/wiki/Raid_(2018_film)
...                                                 ...
1600               https://en.wikipedia.org/wiki/Kasoor
1601     https://en.wikipedia.org/wiki/Maya_(2001_film)
1607  https://en.wikipedia.org/wiki/Nayak_(2001_Hind...
1621              https://en.wikipedia.org/wiki/Tum_Bin
1623             https://en.wikipedia.org/wiki/Zubeidaa

                               title_y                    original_title  \
11                           Gully Boy                         Gully Boy
34                       Yeh Hai India                     Yeh Hai India
37                          Article 15                        Article 15
87                             Aiyaary                           Aiyaary
96                                Raid                              Raid
...                                ...                               ...
1600                            Kasoor                            Kasoor
1601                              Maya                              Maya
1607              Nayak: The Real Hero              Nayak: The Real Hero
1621  Tum Bin...: Love Will Find a Way  Tum Bin...: Love Will Find a Way
1623                          Zubeidaa                          Zubeidaa

      is_adult  year_of_release runtime                   genres  imdb_rating  \
11           0             2019     153              Drama|Music          8.2
34           0             2017     128   Action|Adventure|Drama          5.7
37           0             2019     130              Crime|Drama          8.3
87           0             2018     157          Action|Thriller          5.2
96           0             2018     122       Action|Crime|Drama          7.4
...        ...              ...     ...                      ...          ...
1600         0             2001     151   Drama|Mystery|Thriller          6.0
1601         0             2001     105                    Drama          7.0
1607         0             2001     187    Action|Drama|Thriller          7.8
1621         0             2001     158            Drama|Romance          7.5
1623         0             2001     153  Biography|Drama|History          6.2

      imdb_votes                                              story  \
11         22440  Gully Boy is a film about a 22-year-old boy "M...
34           169  Yeh Hai India  follows the story of a 25 years...
37         13417  In the rural heartlands of India  an upright p...
87          3538  General Gurinder Singh comes with a proposal t...
96         13159  Set in the 80s in Uttar Pradesh  India  Raid i...
...          ...                                                ...
1600         801  Shekar Saxena is arrested and charged with the...
1601         277  For 12 year-old Maya  life is very simple in h...
1607       12522  Employed as a camera-man at a popular televisi...
1621        2879  Shekar and Amar meet at a party where Amar ask...
1623        1384  The film begins with Riyaz (Rajat Kapoor)  Zub...

                                                summary  \
11    A coming-of-age story based on the lives of st...
34    Yeh Hai India  follows the story of a 25 years...
37    In the rural heartlands of India  an upright p...
87    After finding out about an illegal arms deal  ...
96    A fearless income tax officer raids the mansio...
...                                                 ...
1600  Shekhar appoints Simran  a lawyer with an impe...
1601  MAYA is a coming of age story set against an '...
1607  A man accepts a challenge by the chief ministe...
1621  Shekhar accidentally kills his associate Amar ...
1623  Zubeidaa  an aspiring Muslim actress  marries ...

                                                tagline  \
11                                    Apna Time Aayega!
34                              A Film for Every Indian
37               Farq Bahut Kar Liya| Ab Farq Laayenge.
87                                The Ultimate Trickery
96                  Heroes don't always come in uniform
...                                                 ...
1600                             A dangerous passion...
1601  A child's innocence shattered by unreal tradit...
1607                                    Fight the power
1621                               Love will find a way
1623                            The Story of a Princess

                                                 actors  \
11    Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...
34     Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|
37    Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...
87    Sidharth Malhotra|Manoj Bajpayee|Rakul Preet S...
96    Ajay Devgn|Saurabh Shukla|Ileana D'Cruz|Amit S...
...                                                 ...
1600  Divya Dutta|Sucheta Paushe|Lisa Ray|Apoorva Ag...
1601  Anant Nag|Mita Vasisht|Nitya Shetty|Nikhil Yad...
1607  Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...
1621  Priyanshu Chatterjee|Himanshu Malik|Sandali Si...
1623  Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...

             wins_nominations               release_date Country lead_actor
11     6 wins & 3 nominations     14 February 2019 (USA)   India    Ranveer
34      2 wins & 1 nomination        24 May 2019 (India)   India      Gavie
37                      1 win         28 June 2019 (USA)   India  Ayushmann
87               1 nomination     16 February 2018 (USA)   India   Sidharth
96     2 wins & 3 nominations      16 March 2018 (India)   India       Ajay
...                       ...                        ...     ...        ...
1600            2 nominations    2 February 2001 (India)   India      Divya
1601   2 wins & 4 nominations  16 January 2002 (Belgium)   India      Anant
1607            2 nominations   7 September 2001 (India)   India       Anil
1621            6 nominations       13 July 2001 (India)   India  Priyanshu
1623  3 wins & 13 nominations    19 January 2001 (India)   India    Karisma

[298 rows x 20 columns]>

In [139]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

Impostant DataFrame Functions

In [138]:
ipl[]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [140]:
ipl["ID"].astype("int32")

0      1312200
1      1312199
2      1312198
3      1312197
4      1304116
        ...
945     335986
946     335985
947     335984
948     335983
949     335982
Name: ID, Length: 950, dtype: int32

In [141]:
#to do permanent change
ipl["ID"] = ipl["ID"].astype("int32")

In [143]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB